package engine

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"sync"
	"sync/atomic"
	"time"

	"github.com/raqueeb/kvstore/internal/config"
	"github.com/raqueeb/kvstore/internal/snapshot"
	"github.com/raqueeb/kvstore/internal/store"
	"github.com/raqueeb/kvstore/internal/wal"
)

// Errors surfaced to the dispatcher, which maps them to protocol statuses.
var (
	ErrReadOnly = errors.New("engine: instance is a read-only replica")
	ErrOOM      = store.ErrOOM
	ErrClosed   = errors.New("engine: closed")
)

// Engine is the durable single-node store: the composition of the store, the
// WAL, snapshots and the background controllers.
//
// DEVIATION FROM DESIGN.md §13, recorded in docs/DECISIONS.md ADR-010: the
// design sketches this composition inside internal/server. It lives in its
// own package instead, for three reasons — the crash and differential tests
// can drive a full durable engine without opening a socket; the replication
// code in internal/cluster needs the same composition and would otherwise
// import the network layer; and internal/server stays purely about
// connections and framing. The dependency rule the design actually cares
// about (protocol, store and wal know nothing of each other) is preserved:
// this package is the only thing that composes them, exactly as intended.
type Engine struct {
	cfg   config.Config
	log   *slog.Logger
	store *store.Store
	wal   *wal.Writer
	clock store.Clock
	lock  *DirLock

	sweeper *store.Sweeper
	wheel   *store.WheelExpirer

	// gate bounds in-flight mutations so that the WAL queue send inside the
	// shard lock can never block. Acquired BEFORE the shard lock; that
	// ordering is what keeps the "no blocking under a shard lock" rule
	// intact while still letting LSN assignment and the memory apply be
	// atomic per key.
	gate chan struct{}

	// evictQ carries deletes generated by the store itself (active expiry
	// and memory-pressure eviction) out to the WAL and to replicas. It has
	// to be a queue rather than a direct WAL submit because the store fires
	// these callbacks while holding a shard lock.
	evictQ     chan evictEvent
	evictWG    sync.WaitGroup
	evictDrops atomic.Uint64

	// Replication fan-out. Registered by internal/cluster when this node is
	// a primary; nil otherwise.
	replMu    sync.RWMutex
	replFeeds map[int64]chan wal.Record
	replNext  atomic.Int64

	readOnly atomic.Bool
	closed   atomic.Bool

	clusterStats atomic.Pointer[func() json.RawMessage]

	mutations   atomic.Uint64
	lastSnapLSN atomic.Uint64
	snapshots   atomic.Uint64
	snapMu      sync.Mutex

	recovery     RecoveryReport
	resumePath   string
	resumeOffset int64

	ctx    context.Context
	cancel context.CancelFunc
	bgWG   sync.WaitGroup
}

type evictEvent struct {
	key    []byte
	reason store.EvictReason
}

// RecoveryReport describes what happened at startup. Logged in full, and
// exposed through STATS, because "recovery quietly did something" is not an
// acceptable operational story.
type RecoveryReport struct {
	SnapshotPath      string        `json:"snapshot_path"`
	SnapshotLSN       uint64        `json:"snapshot_lsn"`
	SnapshotEntries   uint64        `json:"snapshot_entries"`
	WALSegments       int           `json:"wal_segments"`
	WALRecords        int           `json:"wal_records"`
	WALApplied        int           `json:"wal_applied"`
	WALSkipped        int           `json:"wal_skipped"`
	ExpiredOnLoad     int           `json:"expired_on_load"`
	Truncated         bool          `json:"truncated"`
	TruncatedPath     string        `json:"truncated_path"`
	TruncatedAtOffset int64         `json:"truncated_at_offset"`
	TruncateReason    string        `json:"truncate_reason"`
	NextLSN           uint64        `json:"next_lsn"`
	Duration          time.Duration `json:"duration_ns"`
	KeysLoaded        int           `json:"keys_loaded"`
}

// Open recovers a data directory and returns a ready engine.
//
// The order here is DESIGN.md §8 exactly, and it matters:
//
//  1. lock the data dir
//  2. load the newest valid snapshot
//  3. replay WAL records above the snapshot's LSN
//  4. truncate a torn tail / refuse on real corruption
//  5. drop keys that expired while we were down
//  6. open the WAL for append at the last good offset
//  7. start background controllers
//
// The listener is NOT started here. The caller binds it only after Open
// returns, so a client can never observe a half-recovered store.
func Open(cfg config.Config, logger *slog.Logger) (*Engine, error) {
	if logger == nil {
		logger = slog.Default()
	}
	start := time.Now()

	for _, d := range []string{cfg.DataDir, cfg.WALDir(), cfg.SnapshotDir()} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return nil, fmt.Errorf("create %s: %w", d, err)
		}
	}

	lock, err := AcquireDirLock(cfg.LockPath())
	if err != nil {
		return nil, err
	}

	clock := store.NewRealClock()
	seed := cfg.HashSeed
	if seed == 0 {
		seed = store.NewSeed()
	}

	st := store.New(store.Options{
		Engine:       cfg.Engine,
		Shards:       cfg.Shards,
		Seed:         seed,
		MaxMemory:    cfg.MaxMemory,
		LowWater:     cfg.LowWaterMark(),
		Policy:       cfg.Policy,
		ExactLRU:     cfg.ExactLRU,
		EvictSampleK: cfg.EvictSampleK,
		EvictBatch:   cfg.EvictBatchMax,
		ActorQueue:   cfg.ActorQueue,
		Clock:        clock,
	})

	ctx, cancel := context.WithCancel(context.Background())
	e := &Engine{
		cfg:       cfg,
		log:       logger,
		store:     st,
		clock:     clock,
		lock:      lock,
		gate:      make(chan struct{}, maxInt(cfg.WALQueueDepth/2, 64)),
		evictQ:    make(chan evictEvent, 8192),
		replFeeds: make(map[int64]chan wal.Record),
		ctx:       ctx,
		cancel:    cancel,
	}
	if cfg.Role == config.RoleReplica {
		e.readOnly.Store(true)
	}

	report, err := e.recover()
	if err != nil {
		cancel()
		st.Close()
		lock.Release()
		return nil, err
	}

	// The WAL writer resumes appending at the last good offset. Doing this
	// after replay (rather than opening a fresh segment) keeps LSNs dense
	// and avoids leaving a trail of tiny segments across restarts.
	w, err := wal.Open(wal.Options{
		Dir:             cfg.WALDir(),
		Fsync:           cfg.Fsync,
		SegmentSize:     cfg.SegmentSize,
		GroupCommitMax:  cfg.GroupCommitMax,
		GroupCommitWait: cfg.GroupCommitWait,
		QueueDepth:      cfg.WALQueueDepth,
		StartLSN:        report.NextLSN,
		ResumePath:      e.resumePath,
		ResumeOffset:    e.resumeOffset,
		NowMs:           clock.NowMillis,
	})
	if err != nil {
		cancel()
		st.Close()
		lock.Release()
		return nil, fmt.Errorf("open wal: %w", err)
	}
	e.wal = w

	report.Duration = time.Since(start)
	report.KeysLoaded = st.Len()
	e.recovery = report

	// Only now wire the eviction callback: during replay we do not want
	// recovery-time evictions generating WAL records.
	st.SetOnEvict(e.onStoreEvict)
	e.evictWG.Add(1)
	go e.drainEvictQueue()

	e.startBackground()

	logger.Info("recovery complete",
		"duration", report.Duration,
		"keys", report.KeysLoaded,
		"snapshot_lsn", report.SnapshotLSN,
		"wal_records", report.WALRecords,
		"wal_applied", report.WALApplied,
		"expired_on_load", report.ExpiredOnLoad,
		"next_lsn", report.NextLSN,
		"truncated", report.Truncated)
	if report.Truncated {
		logger.Warn("torn tail truncated during recovery",
			"path", report.TruncatedPath,
			"offset", report.TruncatedAtOffset,
			"reason", report.TruncateReason)
	}
	return e, nil
}

func (e *Engine) recover() (RecoveryReport, error) {
	var rep RecoveryReport

	// Step 2: newest valid snapshot.
	loaded := 0
	hdr, path, err := snapshot.LoadNewestValid(e.cfg.SnapshotDir(), func(en snapshot.Entry) error {
		// Recovery is single-threaded, but it goes through the normal store
		// API so that memory accounting and the TTL index are built exactly
		// as they would be by live traffic. A separate "load path" that
		// bypasses them is how accounting drift gets shipped.
		if err := e.store.Set(en.Key, en.Value, en.ExpireAtMs); err != nil {
			return fmt.Errorf("snapshot entry rejected by the store: %w", err)
		}
		loaded++
		return nil
	})
	switch {
	case err == nil:
		rep.SnapshotPath = path
		rep.SnapshotLSN = hdr.LastIncludedLSN
		rep.SnapshotEntries = hdr.EntryCount
		e.lastSnapLSN.Store(hdr.LastIncludedLSN)
	case errors.Is(err, snapshot.ErrNoSnapshot):
		// Normal on a fresh data directory.
	default:
		return rep, fmt.Errorf("load snapshot: %w", err)
	}

	// Steps 3-6: replay the WAL above the snapshot point.
	res, err := wal.Replay(e.cfg.WALDir(), rep.SnapshotLSN, e.cfg.UnsafeTruncate, func(r wal.Record) error {
		return e.applyRecord(r)
	})
	if err != nil {
		return rep, err
	}
	rep.WALSegments = res.Segments
	rep.WALRecords = res.Records
	rep.WALApplied = res.Applied
	rep.WALSkipped = res.Skipped
	rep.Truncated = res.Truncated
	rep.TruncatedPath = res.TruncatedPath
	rep.TruncatedAtOffset = res.TruncatedAt
	rep.TruncateReason = res.TruncateReason
	rep.NextLSN = res.NextLSN
	e.resumePath, e.resumeOffset = res.ResumePath, res.ResumeOffset

	// Step 7: drop everything that expired while the process was down.
	// Without this, a key with a 10-second TTL written before a two-hour
	// outage would be resurrected and occupy memory until something read it.
	rep.ExpiredOnLoad = e.dropExpired()
	return rep, nil
}

// applyRecord replays one WAL record into the store. No WAL write, no
// locking beyond the store's own: recovery is single-threaded.
func (e *Engine) applyRecord(r wal.Record) error {
	switch r.Type {
	case wal.RecSet:
		return e.store.Set(r.Key, r.Value, r.ExpireAtMs)
	case wal.RecDelete:
		e.store.Delete(r.Key)
		return nil
	case wal.RecExpire:
		e.store.Expire(r.Key, r.ExpireAtMs)
		return nil
	case wal.RecSegmentHdr:
		return nil
	default:
		return fmt.Errorf("engine: cannot replay record type %s", r.Type)
	}
}

func (e *Engine) dropExpired() int {
	// Note this must NOT go through store.Range, which filters expired
	// entries out by design. See Store.PurgeExpired.
	return e.store.PurgeExpired()
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
